=encoding utf8

=head1 NAME

Sdoc - Auszeichnungssprache für Druck- und Online-Dokumente

=head1 DESCRIPTION

Sdoc ist eine leichtgewichtige Auszeichnungssprache zum Erstellen von
Dokumenten. Ein Dokument, das in Sdoc geschrieben ist, kann portabel
in eine Online-Fassung (HTML) und in eine Druck-Fassung (PDF)
übersetzt werden.

Die Online-Fassung ist für die Wiedergabe in einem Webbrowser gedacht.
Dass Aussehen des Dokuments kann via CSS gestaltet werden.

Die Druck-Fassung wird von LaTeX gesetzt und besitzt eine entsprechend
hohe Qualität für die Wiedergabe auf Papier. In einem PDF-Viewer kann
in der Druck-Fassung interaktiv navigiert werden, da sie, ebenso wie
die Online-Fassung, mit Hyperlinks versehen ist.

=head1 AUTHOR

Frank Seitz, L<http://fseitz.de/>

=head1 COPYRIGHT

Copyright (C) 2020 Frank Seitz
